p1 <- ggplot(dfa, aes(x = as.Date(ORDER_DATE, "%Y-%m-%d"), y = as.Date(SHIPPED_DATE, "%Y-%m-%d"), color = as.factor(UNIT_PRICE))) + geom_point() + facet_wrap(~CUSTOMER_STATE) 
p2 <- ggplot(dfa, aes(x = as.Date(ORDER_DATE, "%Y-%m-%d"), y = as.Date(SHIPPED_DATE, "%Y-%m-%d"), color = as.factor(TITLE))) + geom_point() + facet_wrap(~CUSTOMER_STATE) 
p3 <- ggplot(dfa, aes(x = as.Date(ORDER_DATE, "%Y-%m-%d"), y = as.Date(SHIPPED_DATE, "%Y-%m-%d"), color = as.factor(ARTIST))) + geom_point() + facet_wrap(~CUSTOMER_STATE) 

plc <- ggplot(dfc, aes(x = CUSTOMER_STATE)) + geom_histogram()
plo <- ggplot(dfo, aes(x = CUSTOMER_ID)) + geom_histogram()
pli <- ggplot(dfi, aes(x = ITEM_ID, y = UNIT_PRICE, color = ARTIST)) + geom_bar(stat = "identity")
pld <- ggplot(dfd, aes(x = ORDER_ID)) + geom_histogram()

png('./02_Visualizations/Plot1.png')
plot(p1)
dev.off()
png('./02_Visualizations/Plot2.png')
plot(p2)
dev.off()
png('./02_Visualizations/Plot3.png')
plot(p3)
dev.off()
png('./02_Visualizations/PlotC.png')
plot(plc)
dev.off()
png('./02_Visualizations/plotO.png')
plot(plo)
dev.off()
png('./02_Visualizations/PlotI.png')
plot(pli)
dev.off()
png('./02_Visualizations/PlotD.png')
plot(pld)
dev.off()